---
language: python
python: "2.7"
sudo: true

env:
  - SITE=test.yml

before_install:
  - sudo apt-get update -qq 1>/dev/null

install:
  # Install Ansible.
  - pip install ansible 1>/dev/null

  # modif ansible.cfg chemin des roles
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Check de la syntax role/playbook
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"

  # lancement role/playbook avec ansible-playbook
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo"

  # TDD pour role/playbook, check si idempotent.
  #- >
  #  ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo
  #  | grep -q 'changed=0.*failed=0'
  #  && (echo 'Idempotence test: pass' && exit 0)
  #  || (echo 'Idempotence test: fail' && exit 1)

# TODO partie event et hooks si on souhaiterais diffuser avec galaxy

notifications:
  webhooks: https://<patry.repos>/api/v1/notifications/
